"""add video_path to audioproject

Revision ID: 426cb94e5675
Revises: 0c3f703161ca
Create Date: 2026-06-10 16:12:29.643609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '426cb94e5675'
down_revision: Union[str, Sequence[str], None] = '0c3f703161ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audioproject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audioproject', schema=None) as batch_op:
        batch_op.drop_column('video_path')

    # ### end Alembic commands ###
